### ISSUE TITLE
Implement Naive Grounding

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#15]
From the e-mail

>Naive grounding: no es ideal, pero no siempre podremos usar el ASP grounder (e.g. when functions available, etc.). Un punto interesante es si queremos "forzar" el uso del ASP grounder when possible, e.g. by reformulating the problem into STRIPS without functions (just for the purpose of feeding it into the ASP module), and then extracting the info from there.

**Tasks**:
 - [x] Define output format
 - [x] Implement state variable calculation procedure
 - [x] Implement action grounding procedure
 - [x] Implement universal quantifier elimination
 - [x] Implement constraint grounding procedure
 - [ ] Implement HDF5 writer for storing groundings of symbols

**Comment by gfrances** [comment]
@miquelramirez, what's the status of the idea of the "HDF5 writer"? Should we file that as a separate "enhancement" issue and close this one? Sounds like a potentially interesting idea, although I'm not sure I'd prioritize that at least until we have some clear use case, i.e. some domain where storing / retrieving the groundings is what kills the performance (perhaps we already have that? excuse my ignorance. Although thinking about it, if we have that, not sure that clingo would ever be able to tackle it??)

**Comment by miquelramirez** [comment]
This was an old idea, no longer relevant.
