### ISSUE TITLE
Implement Grounding via compilation into ASP

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#16]
From the e-mail:
> ASP-based grounding: migrar tu interfaz con gringo para que en vez de ocuparse de parsear el PDDL, tome una representación del problema en Tarski, y haga el reachability analysis. Por acabar de detaller en qué formato exactamente tiene que sacar output.

**Tasks**:
 - [x] Review existing ASP-based grounder and identify key components
 - [ ] Define output format
 - [x] Refactor ASP grounder (if necessary)
 - [x] Write interface adapter for the ASP grounder

**Comment by gfrances** [comment]
This is now merged into the `dev-0.2.0` branch!
