### ISSUE TITLE
Implement PDDL-like parsing

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#17]
From the e-mail:

> Parsing: punto aburrido pero imprescindible - parsear problemas PDDL / FSTRIPS en un formato intermedio. Espero liquidar esto esta semana, adaptando la gramática que ya tenías en el FS+ parser. Esa será nuestra gramática estándar, y nos podremos cargar  todo el código heredado de FD, el parser del ASP preprocessor, etc etc.

**TODO list**:

 - [x] Review existing ANTLR grammar
 - [x] Rewrite callbacks for parsing events to capture the components modelled by ```Tarski``` language and planning problem components
 - [x] Introduce facade that allows to kickstart the parsing process

**Comment by gfrances** [comment]
This is working since long. The ANTLR grammar for FSTRIPS, which includes PDDL, supports now most basic features. I suggest we close this issue and open surrogate issues for those particular features that are not supported yet but we'd like to support (at the moment I can only think of derived predicates)

**Comment by miquelramirez** [comment]
Yep, 100% agreed
